### ISSUE TITLE
colors of menu is not readable perfectly

### ISSUE THREAD

**Issue by SoranKhezri** [ankitmlive/firefly-theme#1]
Colors of menu is not readable perfectly. Menu of right click and submenu of main menu of IDE are not readable. Their color is very low contrast with it's background. How can change it?

**Comment by ankitmlive** [comment]
Thanks for raising an issue, I will fix it in next update

**Comment by ankitmlive** [comment]
Colors are brighter now

**Comment by SoranKhezri** [comment]
> Colors are brighter now

Thanks
