### ISSUE TITLE
Inactive selection color is kind of unreadable 

### ISSUE THREAD

**Issue by DrKGD** [ankitmlive/firefly-theme#10]
If text is selected and the focus changes to another window or functionality (such as the in-editor text find one), the background color will have a greenish background tint which makes the text pretty much unreadable to me.

![immagine](https://user-images.githubusercontent.com/44092476/94997839-25b50200-05ae-11eb-8d79-5c5088a46852.png)
![immagine](https://user-images.githubusercontent.com/44092476/94997855-32395a80-05ae-11eb-8d36-9dc11d82ebc3.png)

All it takes to solve it for me is an update to the `editor.inactiveSelectionBackground` to something else (e.g.` #EBF2FF30`)
![immagine](https://user-images.githubusercontent.com/44092476/94997946-c7d4ea00-05ae-11eb-844d-4eac7d2383dd.png)

The problem presents with the "Firefly Pro" variant, I did not test the other ones. I already tried disabling hardware acceleration with `"disable-hardware-acceleration": true`.

**Comment by ankitmlive** [comment]
Thanks for letting me know, i will fix it in next update.
