### ISSUE TITLE
Italic support

### ISSUE THREAD

**Issue by giovdk21** [ankitmlive/firefly-theme#11]
Hi,
I really like this theme and I was wondering if you could add a variant with italic support also for keywords, etc. in the same way it's implemented in Monokai Pro (see screenshot here: https://monokai.pro/vscode) (I guess, in the same way in Firefly comments are already in italic)

Thanks.

p.s.
thanks also for recommending JetBrains mono, I missed it when it released; currently my favourite is IBM Plex Mono which I'd also recommend if you don't need ligatures :)

**Comment by ankitmlive** [comment]
Glad to know that you find it beautiful and awesome, I am looking forward to your suggestions. I will implement it as soon as possible.

Thanks for the comment.
