### ISSUE TITLE
Can barely see .gitignore'd files 

### ISSUE THREAD

**Issue by etiennebirling** [ankitmlive/firefly-theme#12]
Hello,
looks like your theme makes it particularly hard to find and navigate through files marked in .gitignore
![Screenshot from 2021-06-10 18-26-37](https://user-images.githubusercontent.com/56506213/121562297-9c49af80-ca19-11eb-94c2-4abf0ebb9a12.png)
![Screenshot from 2021-06-10 18-27-16](https://user-images.githubusercontent.com/56506213/121562304-9d7adc80-ca19-11eb-8430-c136c030dcec.png)
Any fix? 
Thanks in advance

**Comment by ankitmlive** [comment]
Thanks for reporting a bug here, I will fix it soon until you can use new firefly pro.Download from releases https://github.com/ankitmlive/firefly-theme/releases/tag/v4.0.0 and install it by going to VsCode> extension > intall from vsix

**Comment by ankitmlive** [comment]
Fixed in latest release.
