### ISSUE TITLE
Selected text has the same color as the selection highligh (HEX editor)

### ISSUE THREAD

**Issue by Gaweringo** [ankitmlive/firefly-theme#13]
When selecting something in the HEX editor the text of the selection highlight and the text color are the same which makes it impossible to read the selected text.

Example:
![A gif showing how the selected text becomes unreadable](https://user-images.githubusercontent.com/40121865/129173841-350de892-f2b8-4e46-a85b-c146a2b7bf77.gif)

![Showing with the dev-tools, that the color of the text and the background are both the same](https://user-images.githubusercontent.com/40121865/129173824-62eaee99-4335-46be-94c8-9b589ab918fd.png)

The colors used:
![The css class (.selected) with both foreground and background using the same color](https://user-images.githubusercontent.com/40121865/129173807-a3d7a7e4-3d6e-458c-9201-22cde3f8c30a.png)

The `--vscode-editor-selectionForeground` should probably stay white:
![The HEX editor with the selected text being  fully white and readable](https://user-images.githubusercontent.com/40121865/129175147-8d1272a9-8124-4ae7-a435-7f6e373c0342.png)

I changed it to this, which I think looks better, with the selection not being entirely gray.
```css
--vscode-editor-selectionBackground: #3d60947d;
--vscode-editor-selectionForeground: #ffffff; /* Standard foreground is: #bac6db */
```
![Code_tDa9GfzsNK](https://user-images.githubusercontent.com/40121865/129176618-ce13a2e6-bb64-4964-a478-3802681433da.png)

**Comment by ankitmlive** [comment]
@Gaweringo Thank's for detailed explanation of the issue, Working on it.
