### ISSUE TITLE
Does not appear in VSCodium

### ISSUE THREAD

**Issue by vhscom** [ankitmlive/firefly-theme#18]
Not sure why, as Gruvbox and others appear (though many others do not). This leaves the only installation option for Linux users of VSCodium to install the file download manually. Not a huge deal but might be nice for others to discover this beautiful theme in the extension marketplace.

![vscodium-firefly-search](https://user-images.githubusercontent.com/97140109/148215235-18a414b8-c424-479d-9d62-ba692522a6a0.png)

![vscodium-gruvbox-search](https://user-images.githubusercontent.com/97140109/148215461-89cdc85f-45ee-445e-9567-a82356ca7f4e.png)

**Comment by vhs-dev** [comment]
Instructions to get listed:
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by ankitmlive** [comment]
This is not an issue, A feature request instead.
