### ISSUE TITLE
Poor readability with JSX / TSX files

### ISSUE THREAD

**Issue by Burkes321** [ankitmlive/firefly-theme#19]
As in the title, the syntax highlighting of react components and regular HTML tags is exactly the same, and it can make it difficult to distinguish them at a glance. Not the biggest issue, I do still use the theme (as a react developer) for my day-to-day use, just would be nice to have them different.

**Comment by ankitmlive** [comment]
Hey @Burkes321 can you please paste a screenshot here, I will solve in this issue in this weekend

**Comment by Burkes321** [comment]
Sorry for the slow reply. I created a fresh react app here, added a `<Component />` and the syntax highlighting is the same. Thanks!
<img width="1241" alt="code screenshot" src="https://user-images.githubusercontent.com/67603046/164413973-a3be05b0-b467-44db-82fc-c79703438f8d.png">

**Comment by LeonLonsdale** [comment]
Any news on this one? Regular HTML and React Components still appear to have the same syntax highlighting
