### ISSUE TITLE
when renaming a file in the tree, you can barely see the selected characters

### ISSUE THREAD

**Issue by zdj** [ankitmlive/firefly-theme#2]
In the screenshot below, I have selected all but the file extension.

![Screen Shot 2020-02-07 at 6 38 22 AM](https://user-images.githubusercontent.com/4109933/74026586-81be7c80-4974-11ea-998c-9234010cf26d.png)

**Comment by camlent** [comment]
Thanks for the support.
We will fix this issue asap.
@zdj

**Comment by ankitmlive** [comment]
Fixed! Kindly update

**Comment by zdj** [comment]
👍 great theme
