### ISSUE TITLE
Firefly Pro Bright - too bright for eye health

### ISSUE THREAD

**Issue by ffckaburga** [ankitmlive/firefly-theme#20]
Please decrease the amount of brightness a little bit in the Firefly Pro Bright edition, blues, oranges and yellows are really hurting eyes.

**Comment by Florunioo** [comment]
It is perfect I would say, just lower the brightness of ur screen.

**Comment by ankitmlive** [comment]
@ffckaburga @Florunioo  thanks guys for the issues, I will try to fix these issue ASAP, collaboration is also accepted is someone interested 😄

**Comment by ankitmlive** [comment]
As described by @Florunioo It is related to monitor brightness not an issue on theme colors.
