### ISSUE TITLE
Selection highlight on blue color fonts

### ISSUE THREAD

**Issue by ozzyjr** [ankitmlive/firefly-theme#3]
When I select text that is blue, the background color appears to disappear

![Anotação 2020-06-18 105519](https://user-images.githubusercontent.com/12512993/85029212-6d746280-b152-11ea-88b5-f1cb4153f1a6.png)

![Anotação 2020-06-18 105553](https://user-images.githubusercontent.com/12512993/85029277-80873280-b152-11ea-9251-359429c48ddf.png)

![Anotação 2020-06-18 105630](https://user-images.githubusercontent.com/12512993/85029284-8250f600-b152-11ea-84b3-398870ba8df8.png)

**Comment by ankitmlive** [comment]
I am looking for it @ozzyjr , Thank's for letting me know

**Comment by ankitmlive** [comment]
Issue Fixed

**Comment by ozzyjr** [comment]
Thanks
