### ISSUE TITLE
Consider providing extension in open-vsx.org

### ISSUE THREAD

**Issue by douglasrizzo** [ankitmlive/firefly-theme#9]
http://open-vsx.org is an open registry for extensions targeted towards VSCode-compatible editors, such as VSCodium, the open, MIT-licensed version of VSCode. People who use this open version of VSCode cannot install this extension, as it is only provided in the Microsoft Visual Studio Marketplace.

Providing the extension on open-vsx would allow users of open alternatives to VSCode to install it. Thanks you.

**Comment by ankitmlive** [comment]
Thanks for the suggestion, I will do the same.

**Comment by ankitmlive** [comment]
Can anyway do this for this theme ?, I am still not getting time to do this.
